# Generated by Django 5.2.8 on 2025-12-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complexes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnercomplex',
            name='apartments_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partnercomplex',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnercomplex',
            name='district',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='partnercomplex',
            name='metro',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='partnercomplex',
            name='price_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partnercomplex',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
