# Generated by Django 5.2.8 on 2025-12-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealtyOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(max_length=64, unique=True)),
                ('case_id', models.CharField(blank=True, max_length=64, null=True)),
                ('deal_type', models.CharField(blank=True, max_length=50, null=True)),
                ('property_type', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('deal_status', models.CharField(blank=True, max_length=100, null=True)),
                ('deal_state', models.CharField(blank=True, max_length=100, null=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('last_update_date', models.DateTimeField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('locality_name', models.CharField(blank=True, max_length=150, null=True)),
                ('sub_locality_name', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('metro_name', models.CharField(blank=True, max_length=100, null=True)),
                ('metro_time_on_foot', models.PositiveIntegerField(blank=True, null=True)),
                ('metro_time_on_transport', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('price_base', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('price_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('area_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('area_living', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('area_kitchen', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('area_lot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('area_balcony', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rooms', models.PositiveIntegerField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('floors_total', models.IntegerField(blank=True, null=True)),
                ('ceiling_height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_new_flat', models.BooleanField(default=False)),
                ('is_apartments', models.BooleanField(default=False)),
                ('is_studio', models.BooleanField(default=False)),
                ('building_id', models.CharField(blank=True, max_length=64, null=True)),
                ('building_name', models.CharField(blank=True, max_length=150, null=True)),
                ('building_state', models.CharField(blank=True, max_length=100, null=True)),
                ('building_phase', models.CharField(blank=True, max_length=100, null=True)),
                ('building_type', models.CharField(blank=True, max_length=100, null=True)),
                ('building_section', models.CharField(blank=True, max_length=100, null=True)),
                ('building_material', models.CharField(blank=True, max_length=100, null=True)),
                ('building_year', models.CharField(blank=True, max_length=50, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('decoration_type', models.CharField(blank=True, max_length=100, null=True)),
                ('number_flat', models.CharField(blank=True, max_length=50, null=True)),
                ('entrance', models.CharField(blank=True, max_length=50, null=True)),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('photos', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('reserve_char_1', models.CharField(blank=True, max_length=200, null=True)),
                ('reserve_char_2', models.CharField(blank=True, max_length=200, null=True)),
                ('reserve_char_3', models.CharField(blank=True, max_length=200, null=True)),
                ('reserve_char_4', models.CharField(blank=True, max_length=200, null=True)),
                ('reserve_char_5', models.CharField(blank=True, max_length=200, null=True)),
                ('reserve_text_1', models.TextField(blank=True, null=True)),
                ('reserve_text_2', models.TextField(blank=True, null=True)),
                ('reserve_text_3', models.TextField(blank=True, null=True)),
                ('reserve_text_4', models.TextField(blank=True, null=True)),
                ('reserve_text_5', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-last_update_date', 'internal_id'),
            },
        ),
    ]
